image: ruby:2.3

job:
  script:
  - gem install jekyll
  - jekyll build

job:
  script:
  - gem install jekyll
  - jekyll build

pages:
  script:
  - gem install jekyll
  - jekyll build -d public
  artifacts:
    paths:
    - public
    only:
  - master